spring:
  data:
    mongodb:
       uri: mongodb://localhost:27017/test
       database: spring-test

  logging:
    level:
      root: ERROR
      org.springframework.web: DEBUG
      com.Nataneljpwd: DEBUG

