spring:
  data:
    mongodb:
       uri: mongodb://localhost:27017/test
       database: spring-test

  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create

  redis:
    host: localhost
    port: 6379
    timeout: 2000
    maximum-active-connections: 100

  cache:
    redis:
      time-to-live: 6000


  logging:
    level:
      root: ERROR
      org.springframework.web: DEBUG
      com.Nataneljpwd: DEBUG

